vae_decoder_tiling: fix build issue.
/src/cpp/src/module_genai/modules/md_vae_decoder_tiling.cpp:119:45:   required from here
/usr/include/c++/13/bits/stl_construct.h:119:7: error: no matching function for call to
‘ov::Model::Model(std::vector<std::shared_ptr<ov::Node> >, std::vector<std::shared_ptr<ov::op::v0::Parameter> >)’
  119 |       ::new((void*)__p) _Tp(std::forward<_Args>(__args)...);

Signed-off-by: Zhang, Xiaolin <xiaolin.zhang@intel.com>